name: clients
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  get_it: ^8.0.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  pinput: ^5.0.0
  phone_form_field: ^10.0.3
  flutter_dotenv: ^5.2.1
  toastification: ^2.3.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IBMSans
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100

  assets:
    - assets/strings/
    - assets/icons/
    - assets/svg/
    - assets/images/
    - .env

flutter_assets:
assets_path:
  - assets/images/
  - assets/svg/
output_path: lib/core/constants/
filename: assets.dart
