name: Android Fastlane with Firebase App distribution workflow

on:
  push:
    branches:
      - development

jobs:
  internal_distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-v4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v4-

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Launch Fastlane with Firebase App distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane internal_distribute
        working-directory: android
